import { UserType } from "../../../core/models/User.type";

export const DataAccount: UserType[] = [
  // {
  //   key: "user1",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@1",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role1",
  //     name: "Kế toán",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user2",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@2",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role1",
  //     name: "Kế toán",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user3",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@3",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "inactive",
  //   role: {
  //     key: "role1",
  //     name: "Kế toán",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user4",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@4",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role2",
  //     name: "Bác sĩ",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user5",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@5",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role2",
  //     name: "Bác sĩ",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user6",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@6",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role2",
  //     name: "Bác sĩ",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user7",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@7",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "inactive",
  //   role: {
  //     key: "role2",
  //     name: "Bác sĩ",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user8",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@8",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role3",
  //     name: "Lễ tân",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user9",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@9",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role3",
  //     name: "Lễ tân",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user10",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@10",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role4",
  //     name: "Quản lý",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user11",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@11",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role4",
  //     name: "Quản lý",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user12",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@12",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role5",
  //     name: "Admin",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user13",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@13",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "inactive",
  //   role: {
  //     key: "role5",
  //     name: "Admin",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
  // {
  //   key: "user14",
  //   name: "Nguyễn Văn A",
  //   username: "nguyenvana@14",
  //   password: "password@123",
  //   email: "nguyenvana123@gmail.com",
  //   phone: "0919256712",
  //   status: "active",
  //   role: {
  //     key: "role6",
  //     name: "Super admin",
  //     describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //     user: [],
  //     permission: [],
  //   },
  // },
];
