import { ServiceType } from "../../core/models/Service.type";

export const DataService: ServiceType[] = [
  {
    key: "KIO_01",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [
      {
        id: 2010001,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "finished",
        customer: null,
      },
      {
        id: 2010002,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "processing",
        customer: null,
      },
      {
        id: 2010003,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "finished",
        customer: null,
      },
      {
        id: 2010004,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "absent",
        customer: null,
      },
      {
        id: 2010005,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "finished",
        customer: null,
      },
      {
        id: 2010006,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "processing",
        customer: null,
      },
      {
        id: 2010007,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "finished",
        customer: null,
      },
      {
        id: 2010008,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "finished",
        customer: null,
      },
      {
        id: 2010009,
        start_time: new Date("2021-07-11T14:35:00"),
        end_time: new Date("2021-07-11T18:00:00"),
        service: {
          key: "KIO_01",
          name: "Kiosk",
          describe: "Mô tả dịch vụ nè",
          status_active: "active",
          queue: [],
        },
        device: {
          key: "KIO_01_Device",
          name: "Kiosk Device",
          ip_address: "192.168.1.1",
          status_active: "active",
          status_connection: "connected",
          service_use: "KIO_01",
          username: "admin",
          password: "password",
          category: "kiosk",
        },
        status: "absent",
        customer: null,
      },
    ],
  },
  {
    key: "KIO_02",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
  {
    key: "KIO_03",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "inactive",
    queue: [],
  },
  {
    key: "KIO_04",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
  {
    key: "KIO_05",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
  {
    key: "KIO_06",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
  {
    key: "KIO_07",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
  {
    key: "KIO_08",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "inactive",
    queue: [],
  },
  {
    key: "KIO_09",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
  {
    key: "KIO_10",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "inactive",
    queue: [],
  },
  {
    key: "KIO_11",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "inactive",
    queue: [],
  },
  {
    key: "KIO_12",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
  {
    key: "KIO_13",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "inactive",
    queue: [],
  },
  {
    key: "KIO_14",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
  {
    key: "KIO_15",
    name: "Kiosk",
    describe: "Mô tả dịch vụ nè",
    status_active: "active",
    queue: [],
  },
];
