import { AuditLogType } from "../../../core/models/AuditLog.type";

export const DataAuditLog: AuditLogType[] = [
  // {
  //   key: "log-1",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user2",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@2",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role1",
  //       name: "Kế toán",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-2",
  //   impact_time: new Date("2021-12-03T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user4",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@4",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role2",
  //       name: "Bác sĩ",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-3",
  //   impact_time: new Date("2021-12-05T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user2",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@2",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role1",
  //       name: "Kế toán",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-4",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user1",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@1",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role1",
  //       name: "Kế toán",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-5",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user9",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@9",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role3",
  //       name: "Lễ tân",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-6",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user9",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@9",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role3",
  //       name: "Lễ tân",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-7",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user9",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@9",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role3",
  //       name: "Lễ tân",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-8",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user9",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@9",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role3",
  //       name: "Lễ tân",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-10",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user4",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@4",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role2",
  //       name: "Bác sĩ",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-11",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user11",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@11",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role4",
  //       name: "Quản lý",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-12",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user11",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@11",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role4",
  //       name: "Quản lý",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-13",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user7",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@7",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "inactive",
  //     role: {
  //       key: "role2",
  //       name: "Bác sĩ",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-14",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user7",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@7",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "inactive",
  //     role: {
  //       key: "role2",
  //       name: "Bác sĩ",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-15",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user7",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@7",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "inactive",
  //     role: {
  //       key: "role2",
  //       name: "Bác sĩ",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
  // {
  //   key: "log-16",
  //   impact_time: new Date("2021-12-01T15:12:17"),
  //   ip_address: "192.168.3.1",
  //   note: "Cập nhật thông tin dịch vụ DV_01",
  //   user: {
  //     key: "user14",
  //     name: "Nguyễn Văn A",
  //     username: "nguyenvana@14",
  //     password: "password@123",
  //     email: "nguyenvana123@gmail.com",
  //     phone: "0919256712",
  //     status: "active",
  //     role: {
  //       key: "role6",
  //       name: "Super admin",
  //       describe: "Thực hiện nhiệm vụ về thống kê số liệu và tổng hợp số liệu",
  //       user: [],
  //       permission: [],
  //     },
  //   },
  // },
];
