import { QueueType } from "../../core/models/Queue.type";

export const DataQueue: QueueType[] = [
  // {
  //   id: 2010001,
  //   customer: {
  //     id: "1",
  //     name: "Lê Huỳnh Ái Vân",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "timMach",
  //     name: "Khám tim mạch",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "processing",
  //   device: {
  //     key: "KIO_01",
  //     name: "Kiosk",
  //     ip_address: "192.168.0.100",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010002,
  //   customer: {
  //     id: "2",
  //     name: "Huỳnh Ái Vân",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "sanPhuKhoa",
  //     name: "Khám sản - Phụ khoa",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "finished",
  //   device: {
  //     key: "KIO_01",
  //     name: "Kiosk",
  //     ip_address: "192.168.0.100",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010003,
  //   customer: {
  //     id: "3",
  //     name: "Lê Ái Vân",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "rangHamMat",
  //     name: "Khám răng hàm mặt",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "processing",
  //   device: {
  //     key: "KIO_02",
  //     name: "Hệ thống",
  //     ip_address: "192.168.0.101",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010004,
  //   customer: {
  //     id: "4",
  //     name: "Nguyễn Ái Vân",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "taiMuiHong",
  //     name: "Khám tai mũi họng",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "processing",
  //   device: {
  //     key: "KIO_02",
  //     name: "Hệ thống",
  //     ip_address: "192.168.0.101",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010005,
  //   customer: {
  //     id: "5",
  //     name: "Trần Thị Ái Vân",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "hoHop",
  //     name: "Khám hô hấp",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "processing",
  //   device: {
  //     key: "KIO_01",
  //     name: "Kiosk",
  //     ip_address: "192.168.0.100",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010006,
  //   customer: {
  //     id: "6",
  //     name: "Lê Huỳnh Nghĩa",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "tongQuat",
  //     name: "Khám tổng quát",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "finished",
  //   device: {
  //     key: "KIO_02",
  //     name: "Hệ thống",
  //     ip_address: "192.168.0.101",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010007,
  //   customer: {
  //     id: "7",
  //     name: "Lê Huỳnh Ái Vân",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "taiMuiHong",
  //     name: "Khám tai mũi họng",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "finished",
  //   device: {
  //     key: "KIO_01",
  //     name: "Kiosk",
  //     ip_address: "192.168.0.100",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010008,
  //   customer: {
  //     id: "8",
  //     name: "Phạm Văn Mạnh",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "tongQuat",
  //     name: "Khám tổng quát",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-08T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "absent",
  //   device: {
  //     key: "KIO_02",
  //     name: "Hệ thống",
  //     ip_address: "192.168.0.101",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010009,
  //   customer: {
  //     id: "9",
  //     name: "Lê Thị Cẩm Tiên",
  //     email: "aivan@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "taiMuiHong",
  //     name: "Tai mũi họng",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "finished",
  //   device: {
  //     key: "KIO_02",
  //     name: "Hệ thống",
  //     ip_address: "192.168.0.101",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010010,
  //   customer: {
  //     id: "10",
  //     name: "Nguyễn Minh Nhật",
  //     email: "nhatnguyen@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "rangHamMat",
  //     name: "Khám răng hàm mạch",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "processing",
  //   device: {
  //     key: "KIO_02",
  //     name: "Hệ thống",
  //     ip_address: "192.168.0.101",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
  // {
  //   id: 2010011,
  //   customer: {
  //     id: "11",
  //     name: "Nhật Nguyễn Minh",
  //     email: "minhnhat@gmail.com",
  //     phone: "0767375921",
  //     queue: [],
  //   },
  //   service: {
  //     key: "timMach",
  //     name: "Khám tim mạch",
  //     describe: "Mô tả dịch vụ nè",
  //     status_active: "active",
  //     queue: [],
  //   },
  //   start_time: new Date("2021-11-07T14:35:00"),
  //   end_time: new Date("2021-11-12T14:35:00"),
  //   status: "absent",
  //   device: {
  //     key: "KIO_01",
  //     name: "Kiosk",
  //     ip_address: "192.168.0.100",
  //     status_active: "active",
  //     status_connection: "connect",
  //     service_use: "",
  //     username: "",
  //     password: "",
  //     category: "",
  //   },
  // },
];
